### PR TITLE
chore(module dependencies): bump up module dependencies

### PR DESCRIPTION
**Pull request by DarkWeird**
Up Fluid module

### CODE REVIEW

**Review by 4Denthusiast — CHANGES_REQUESTED** [review]
This doesn't actually compile with Fluid version 2.0.0. `FluidHolderWidget` seems to be just an out-of-date duplicate of `FluidContainerWidget` from Fluid, and the references to `fluidRegistry.getFluidRenderer(...).getFluidName()` should be replaced with just `fluidRegistry.getDisplayName(...)`.

I originally didn't make these changes just because WoodAndStone seemed to already be out-of-date.

**Comment by DarkWeird** [comment]
> This doesn't actually compile with Fluid version 2.0.0. `FluidHolderWidget` seems to be just an out-of-date duplicate of `FluidContainerWidget` from Fluid, and the references to `fluidRegistry.getFluidRenderer(...).getFluidName()` should be replaced with just `fluidRegistry.getDisplayName(...)`.
> 
> I originally didn't make these changes just because WoodAndStone seemed to already be out-of-date.

Ok, thx. I Will do.
Build not checked, because i'm on omega workspace, which is half broken after nui extraction.
+ Module have nui extraction problems.

It is in omega... Then it is not archivied... Then it is must works :(

**Comment by DarkWeird** [comment]
@4Denthusiast 
how reimplement FluidRenderer#renderFluid?

**Comment by 4Denthusiast** [comment]
> @4Denthusiast
> how reimplement FluidRenderer#renderFluid?

You can use the example of https://github.com/Terasology/Fluid/pull/19/files#diff-5fea087d7450d17aa2e43ee39da7bfcf. I assume you need this for FluidHolderWidget though? That should just be removed instead. FluidContainerWidget does the same thing (I think even with the exact same interface), so it can just be replaced to avoid duplicate code.

**Comment by skaldarnar** [comment]
We're phasing out the old TtA modules... 😭 Closing this one as it has gotten stale, but I'm pretty sure we'll salvage a bunch of things 🙃

**Pull request closed without merging**
