### PR TITLE
Several bugfixes related to CookingStation and HerbalismStation. Several new items added.

### PR DESCRIPTION
**Pull request by xrtariq2594**
# Description of Changes

## Additions

**Normal Item Prefabs:**
* CookedBrownRice
* DebugHerb (to be removed)
* HealingHerb
* HealthHerb (to be removed)
* PortableBasicWoodcrafting
* PortableCookingStation
* PortableHerbalismStation
* StoneLongKnife
* StoneLongKnifeBlade

**Potion Prefabs:**
* HealPotion (will restore health in the next revision)

**Recipe Prefabs:**
* RecipeHealPotion1
* RecipeCookedBrownRice
* RecipeStoneLongKnife
* RecipeStoneLongKnifeBlade

Images for BrownRice, CookedBrownRice, HealPotion1, HealthHerb, PortableBasicStonecraftingStation, PortableBasicWoodcraftingStation, PortableCookingStation, PortableHerbalismStation, StoneLongKnife, and StoneLongKnifeBlade added. All of them, excluding HealPotion1, were created by modifying the preexisting images present in this module. The HealPotion1 was graphic was created by me.

## Modifications
In the WhiteRice prefab, two instances of "rice" was changed to "whiteRice".

The FluidContainerComponent was replaced with the FluidHolderComponent which functions the same way as before. **NOTE: For modules that depend on this one, make sure any reference to FluidContainerComponent is refactored into FluidHolderComponent.**

I fixed a few issues related to the CookingStation and HerbalismStation. Now, the fluid display (FluidHolderComponent) should (hopefully) not crash the game and actually show up when the stations are open. Plus, the positioning of the FluidHolder UI element was moved slightly.

The ResetStartingInventorySystem's only event handler method "resetStartingInventory" had two required components added to the signature.

Added two new tooltips related to fluid input and output in the CookingStationWindow. They are currently not working as intended.

The RegisterWoodAndStoneRecipes's "addHerbalismWorkstationRecipes" method was modified to allow for dynamic adding of other Herb Potion recipes, as long as they have the new HerbalismStationRecipeComponent in their recipe prefab.

The HerbalismCraftingStationRecipe had two new constructors added, and the PotionRecipeResultFactory internal class modified. This is to facilitate more Herb Potion recipes. 

# How to Test

As this is the first set of revisions, there are several items that may not function as intended. Please report issues.

**Reference Image** (slightly outdated):

cookingstationlabelled

**Begin**
* Create a new world with the base modules required for WoodAndStone.
* Once in the world, spawn 20 Stick, at least 1 WhiteRice, at least 1 BrownRice, 4 HealingHerb, 2 WoodenBucket, 1 PortableCookingStation, and 1 PortableHerbalismStation, using the command in the console "giveItem INSERT_PREFAB_NAME_HERE".
* Find the nearest body of water, and fill up those two WoodenBuckets by switching to them and right-clicking on the water.

**Cooking**
* Open up the PortableCookingStation by right-clicking while it's equipped.
* Place the (filled) WoodenBucket into the fluid input slot. It should show the FluidHolder going from empty to completely filled.
* Remove the WoodenBucket from the fluid output slot.
* Add the WhiteRice and BrownRice to the ingredients input slots.
* Add the Sticks to the fuel slot.
* When the option appears, create one CookedWhiteRice, remove it from the output slot, and one CookedBrownRice, and then remove it as well.
* Eat them by equipping them and right-clicking.
* If the previous steps work, and the hunger meter increases, the test is a success
* Remove all items from the PortableCookingStation (ingredients, buckets, fuel, cooked products).

**Herbalism**
* Open up the PortableHerbalismStation by right-clicking while it's equipped.
* Place the (filled) WoodenBucket into the fluid input slot. It should show the FluidHolder going from empty to completely filled.
* Remove the WoodenBucket from the fluid output slot.
* Add the HealingHerbs to the ingredients input slots.
* Add the Sticks to the fuel slot. If you're out, spawn more by using the command "giveItem Stick" several times.
* When the option appears, create two "Potion"s (indicated by the one that has the HealPotion1.png
graphic).
* Drink them by equipping them and right-clicking.
* If the previous steps work and the potion disappears upon use, this test is a success.

# Credits

I would like to thank @Cervator, @SkySom, and @portokaliu for helping me throughout the process of developing these fixes.

### CODE REVIEW

**Comment by Cervator** [comment]
Thanks again for the great work and the great instructions :-)

I wonder if you have an un-submitted fix somewhere? I still get the same old issue where if I try to scoop water into a bucket I get:

`FluidContainerAssetResolver - Unexpected number of tokens when trying to getAssetData for a fluid container's content: woodandstone:item`

Been that way for some time. Easy fix I'm sure, and since you seem to have been able to get past it I bet you found and fixed something, but maybe the fix is somewhere else? In the Fluid module maybe?

**Comment by xrtariq2594** [comment]
Alright, I have reproduced the warning. The issue is in the FluidContainerAssetResolver class (in the Fluid module). Specifically, the regex for the parameters variable.

**Comment by xrtariq2594** [comment]
Okay, a fix for the issue is up here: [https://github.com/Terasology/Fluid/pull/7](url).

**Comment by Cervator** [comment]
Tested along a little further. Turns out I was accidentally using the fuel slot for the water, so I missed that it worked anyway.

This time it is looking better :-)

I did hit one interesting error - if I requested a second PortableCookingStation I hit an NPE:

```
00:28:24.693 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.heat.HeatUtils.getEntityBlocks(HeatUtils.java:122)
	at org.terasology.heat.HeatUtils.getPotentialHeatedBlocksForProducer(HeatUtils.java:154)
	at org.terasology.heat.HeatTriggeringSystem.beforeProducerRemoved(HeatTriggeringSystem.java:124)
	at org.terasology.heat.HeatTriggeringSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.destroy(PojoEntityManager.java:539)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.destroy(BaseEntityRef.java:138)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItemToSlots(InventoryAuthoritySystem.java:215)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:321)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:298)
	at org.terasology.logic.inventory.ItemCommands.giveItem(ItemCommands.java:67)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.terasology.logic.console.commandSystem.AbstractCommand.execute(AbstractCommand.java:237)
	at org.terasology.logic.console.ConsoleImpl.execute(ConsoleImpl.java:232)
	at org.terasology.logic.console.ConsoleImpl.execute(ConsoleImpl.java:196)
	at org.terasology.logic.console.ui.ConsoleScreen.lambda$initialise$100(ConsoleScreen.java:79)
	at org.terasology.logic.console.ui.ConsoleScreen$$Lambda$242/1060921037.onActivated(Unknown Source)
	at org.terasology.rendering.nui.widgets.UIText.onKeyEvent(UIText.java:318)
	at org.terasology.logic.console.ui.UICommandEntry.onKeyEvent(UICommandEntry.java:83)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.keyEvent(NUIManagerInternal.java:604)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.input.InputSystem.sendKeyEvent(InputSystem.java:475)
	at org.terasology.input.InputSystem.processKeyboardInput(InputSystem.java:425)
	at org.terasology.input.InputSystem.update(InputSystem.java:272)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:195)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
	at org.terasology.engine.Terasology.main(Terasology.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
00:28:24.693 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] You received an item of WoodAndStone:PortableCookingStation
```

That may be from already having used the first one (so it still had water in its etc) yet they really wanted to stack in the same slot. Probably they shouldn't be stackable after they've become unique. Same with the water buckets when filled. There are a few similar items that work like that. It didn't happen again if I dropped both then requested a new one so it would get its own stack. 

Although a couple more exceptions then showed up as I tried to use the third one (first one got hit with the issue where the temperature gets stuck on empty) despite there being more fuel available - maybe this happened when the two loose ones on the ground despawned?

```
00:30:26.162 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] You received an item of WoodAndStone:PortableCookingStation
00:30:49.768 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.heat.HeatUtils.getEntityBlocks(HeatUtils.java:122)
	at org.terasology.heat.HeatUtils.getPotentialHeatedBlocksForProducer(HeatUtils.java:154)
	at org.terasology.heat.HeatTriggeringSystem.beforeProducerRemoved(HeatTriggeringSystem.java:124)
	at org.terasology.heat.HeatTriggeringSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.destroy(PojoEntityManager.java:539)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.destroy(BaseEntityRef.java:138)
	at org.terasology.logic.common.lifespan.LifespanSystem.update(LifespanSystem.java:46)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
	at org.terasology.engine.Terasology.main(Terasology.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
00:30:54.336 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.heat.HeatUtils.getEntityBlocks(HeatUtils.java:122)
	at org.terasology.heat.HeatUtils.getPotentialHeatedBlocksForProducer(HeatUtils.java:154)
	at org.terasology.heat.HeatTriggeringSystem.beforeProducerRemoved(HeatTriggeringSystem.java:124)
	at org.terasology.heat.HeatTriggeringSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.destroy(PojoEntityManager.java:539)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.destroy(BaseEntityRef.java:138)
	at org.terasology.logic.common.lifespan.LifespanSystem.update(LifespanSystem.java:46)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
	at org.terasology.engine.Terasology.main(Terasology.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

None the less the actual cooking worked! Om nom nom  :rice:

First herb potion has a rice bowl texture? Was unsure if that was expected. Both have "specie: null" on them, probably related to a goofy interaction with Genome?

Successfully brewed and drank the two potions although neither seemed to do anything (yet)

Also, noticed there is a comma missing in `HealthHerb.prefab` line 17 :-)

Awesome stuff!

**Comment by xrtariq2594** [comment]
Good work on the testing. After conducting my own tests, the "getEntityBlocks" method errors are not causing the burner to suddenly stop working (or accepting fuel).

I haven't figured out how to make items non-stackable yet. Removing the stackID causes the items to glitch out. The rice bowl texture is intentional as I didn't have another unique texture at the time.

The "specie: null" is due to me hardcoding the Genome values for the predefined potions, and the system responding by not recognizing them and thus, setting the specie to null.

**Comment by xrtariq2594** [comment]
With the new commit, a few bugfixes and additions have been made

# Description of Changes

## Additions

**Normal Item Prefabs:**
* QualityWoodenBucket (specifically added to test the FluidContainerAssetResolver)
* RegenHerb
* SwimSpeedHerb
* WalkSpeedHerb

**Potion Prefabs:**
* JumpPotion (doesn't do anything yet)
* RegenPotion (regenerates 3 HP per second for 10 seconds)
* SwimSpeedPotion (doubles swim speed for 10 seconds)
* WalkSpeedPotion (doubles walk speed for 10 seconds)

**Recipe Prefabs:**
* RecipeRegenPotion1
* RecipeSwimSpeedPotion1
* RecipeWalkSpeedPotion1

**Code:**
* PotionCommonEffects (to store the different kinds of effects)

**Systems:**
* HerbalismStationIngredientPredicate

Images for QualityWoodenBucket, QualityWoodenBucketEmpty, RegenHerb, SwimSpeedHerb, and WalkSpeedHerb, added by image-editing the base herb image provided.
Images for RegenPotion1, SwimSpeedPotion1, and WalkSpeedPotion1 were created by me.

## Modifications

The HealPotion will now instantly heal the player for 20 HP upon drinking.

The recipe for the Heal Potion (HealPotion1.prefab) had its recipeComponents fixed to refer to the correct ingredient names, and the requiredTemperature raised from 90 to 150.

PotionComponent now has fields to store the effect name, magnitude, and duration of the potion's effect.

The DrinkPotionAuthoritySystem has received a significant update to allow for it to handle potions that do not have (valid) Genomes. Specifically, now it can manage potions that have the following effects: HEAL, REGEN, WALK_SPEED, and SWIM_SPEED. If it cannot identify the potion's effect, it will default to the DoNothingEffect. The potionConsumed method needs some reworking for the scenario where this happens though.

The RegisterWoodAndStoneRecipes's addHerbalismWorkstationRecipes has been updated to better support the registration of the potion recipes. Registration of the basic HerbPotions has been temporarily disabled for now.

The CookingStationWindow and HerbalismStationWindow UI classes have been updated to include tooltips for many of the UI elements.

The HerbalismCraftingStationRecipe class has updated so that its fifth constructor now uses the new HerbalismStationIngredientPredicate in its addIngredientBehaviour call. This is to ensure that recipe components are properly registered and prevent herbs outside of the recipe requirements from being used to brew potions. Two or three of the constructors will be removed later.

The CookingStation and HerbalismStation UI files have been updated to prevent overlapping of UI elements.

## Deletions

HealthHerb prefab removed. DebugHerb to follow in next commit. 

# How to Test

As this is the second set of revisions, there are several items that may not function as intended. Please report issues.

TO BE ADDED.

# Credits

I would like to thank @Cervator, @SkySom, and @portokaliu for helping me throughout the process of developing these fixes.

**Comment by Cervator** [comment]
Next round of testing really made me appreciate the `search` command like `search herb` to get related names printed to the console :D

Observations:

* The fancy new bucket starts with a see-through hole, and when i fill it then it becomes whole again and looks like an empty bucket? Not sure if that was on purpose. Still actually held water.
* Adding all 4 herbs looks a little odd since they start overflowing the water gauge
* The names visible on the icons are reversed when held - may want to mirror the icons so they show better while held :-)
* Walk and swim speed potions seemed to work, little harder to be sure with swim. Health was good. Regen again a little harder to be sure.
* Noticed the stackable station + NPE is still there, but that's known already

That's all the testing I did for now. Solid enough to merge. Keep at it and feel free to push straight to master, or use PRs for something you want extra testing for :-)

**Pull request merged**
