### PR TITLE
Reorganize PlantPack. Extract AnotherWorldPlants.

### PR DESCRIPTION
**Pull request by Josharias**
This requires https://github.com/Terasology/PlantPack/pull/9 and https://github.com/Terasology/AnotherWorldPlants

### CODE REVIEW

**Comment by Josharias** [comment]
@MarcinSc, any major objections to this?

**Comment by MarcinSc** [comment]
Generally no, question is - is it breaking WoodAndStone further than the seeds planting already?

**Comment by Josharias** [comment]
Not breaking it further,  seeds is just broken at the moment.  I tested without these changes with the same brokenness.

**Comment by MarcinSc** [comment]
Something must have broken it earlier, as it was working at some point. :)

**Comment by Cervator** [comment]
When merging this be sure to add AnotherWorldPlants into https://github.com/Terasology/Index/blob/master/distros/omega/gradle.properties then the next engine build should pick it up :-)

And move it between views in Jenkins + add entry in the game readme. I can do some of that stuff just ping me (or I might notice emails) - hoping *maybe* we can get a stable release out tomorrow along with a fixed launcher ... /me wanders back to surgery table

**Comment by Josharias** [comment]
Not stressing getting it in before next stable release.  I will aim for the one after as it doesn't add anything new to see.

**Pull request merged**
