### PR TITLE
Added JumpSpeedPotion, and events for drinking potions.

### PR DESCRIPTION
**Pull request by xrtariq2594**
A smaller update compared to the previous two. This was made possible by the hard work of @Josharias.

# Description of Changes

## Additions

**Potion Prefabs:**
* JumpSpeedPotion (doubles your jumping height for 10 seconds)

**Recipe Prefabs:**
* RecipeJumpSpeedPotion1 (1 WalkSpeedHerb and 1 SwimSpeedHerb)

**Jump Potion Related:**
* JumpSpeedAlterationEffect (to manage the jumping speed alteration effect)
* JumpSpeedComponent (to store the magnitude of the effect)

**Events:**
* BeforeDrinkPotionEvent (similar to how BeforeHealEvent works)
* DrinkPotionEvent

**Systems:**
* MobilityAlterationSystem (temporary until I move the event handler to the AlterationEffects module, along with JumpSpeedAlterationEffect and JumpSpeedComponent )

Image for JumpSpeedPotion1, which was created by me.

## Modifications

The MULTI_JUMP constant was added to PotionCommonEffects for future advancements.

The DrinkPotionAuthoritySystem was slightly overhauled to take advantage of the DrinkPotionEvent and BeforeDrinkPotionEvent. This should allow for other modules to influence the magnitude and duration of the potion's effects. The expireEffects method will also have to moved to the AlterationEffects module in the near future.

## Deletions

DebugHerb prefab removed.

# Known Isuses

* The burner for either the PortableCookingStation or PortableHerbalismStation may suddenly cease to work, ignoring any extra fuel added to the fuel slot.
* The getEntityBlocks error is caused by the method trying to look for either a BlockComponent or a BlockRegionComponent. Neither of these exist for the portable stations, as they are items.
* The first potionConsumed event handler method in the DrinkPotionAuthoritySystem will fail to work with the predefined potion types due to lack of a proper Genome. Need to add failure checks.

# How to Test

As this is the third set of revisions, there are several items that may not function as intended. Please report issues as you find them.

* Using the instructions given in the previous commit's "Herbalism" section, spawn several SwimSpeedHerbs and WalkSpeedHerbs.
* Make sure that each herb has a unique picture.
* Spawn and prepare the PortableHerbalismStation as usual (add water and fuel).
* Add all of the ingredients into the ingredients slots.
* Take a look at the ingredients list to ensure that three kinds of potions (JumpSpeed, SwimSpeed, and WalkSpeed) are listed.
* Begin crafting several JumpSpeed potions.
* If the burner suddenly breaks down (known issue), remove all of the items from the PortableHerbalismStation, drop it into the world, and repeat step 3.
* Once all the potions are crafted, begin drinking one of the JumpSpeed potions and jump up to verify if the effect matches the above description. You'll probably want to bring some HealPotions or use console commands.
* If all above checks work, the test was a success.

MORE TO BE ADDED.

# Credits

I would like to thank @Cervator, @Josharias, @SkySom, and @portokaliu for helping me throughout the development.

### CODE REVIEW

**Comment by xrtariq2594** [comment]
Alright, I moved over the stuff related to the JumpingSpeed effect over to the AlterationEffects module. So make to grab the latest version of that repo.

**Comment by Cervator** [comment]
Tested this out together with latest AlterationEffects + engine PR for the jump bit. All at once since we got a user on IRC who seemingly hit a jump-related crash (but with lots of other modules enabled) so I figured I'd merge and rebuild to shake that off just in case :-)

Jump force works well! Made a potion and was able to jump much faster. Oddly though I got an exception, but only on the first potion I drank. Drank another couple jump speeds later and no problem. Didn't seem to have an impact,

**Comment by xrtariq2594** [comment]
Hmm, what exception did you get?

**Comment by Cervator** [comment]
Oh, duh, yeah, I had that in my clipboard and forgot to paste it :D

```
18:41:22.633 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.herbalism.system.DrinkPotionAuthoritySystem.potionConsumed(DrinkPotionAuthoritySystem.java:75)
	at org.terasology.herbalism.system.DrinkPotionAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.characters.CharacterSystem.onActivationRequest(CharacterSystem.java:148)
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:213)
	at org.terasology.logic.players.LocalPlayer.activateOwnedEntityAsClient(LocalPlayer.java:174)
	at org.terasology.logic.players.LocalPlayerSystem.onUseItemButton(LocalPlayerSystem.java:358)
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:174)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:328)
	at org.terasology.input.InputSystem.update(InputSystem.java:271)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:195)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
	at org.terasology.engine.Terasology.main(Terasology.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
18:41:23.806 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
```

**Comment by xrtariq2594** [comment]
Yep, that's the third issue I identified on my issues list. It fails due to the lack of a proper Genome. I'll be fixing that in the next revision.

**Comment by Cervator** [comment]
Aahhhh okay! Cool :-)

**Pull request merged**
